# Generated by Django 4.0.4 on 2022-04-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_vote_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
