# Generated by Django 4.0.4 on 2022-04-16 22:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 16, 22, 9, 32, 245471, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
